### ISSUE TITLE
Docker Image yamllint 1.0.2 doesn't exist

### ISSUE THREAD

**Issue by am250360** [actionshub/yamllint#8]
## :ghost: Brief Description

The most recent commit switches the action to use the container image `ghcr.io/actionshub/yamllint:1.0.2`. That image doesn't exist as there is no 1.0.2 release, so the image hasn't been built/tagged. This is causing any project that makes use of the action `actionshub/yamllint@main` to fail.

e.g.
```
  /usr/bin/docker pull ghcr.io/actionshub/yamllint:1.0.2
  Error response from daemon: manifest unknown
Error: Docker pull failed with exit code 1
```

## :pancakes: Action version

`main` (sorry, I know we should be pinned to a release) 

## :tophat: workflow configuration

```
name: Lint Checks
on: [pull_request]
jobs:
  yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run yaml Lint
        uses: actionshub/yamllint@main
```

## Steps To Reproduce

Use `actionshub/yamllint@main` in a workflow

## :police_car: Expected behavior

The yamllint action runs.

Thanks for your help!
